name: url-health-check

on:
  schedule:
    - cron: '0 2 * * *' 
  push:
    branches: ["main"]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1-realdeal.onrender.com/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s

      - name: health check discord
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '❌ The project {{ EVENT_PAYLOAD.repository.full_name }} health check has failed.'

      - name: health check success discord
        if: ${{ success() }}
        uses: Ilshidur/action-discord@master
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '✅ The project {{ EVENT_PAYLOAD.repository.full_name }} health check has succeeded.'
